version: '3'

services:
  mysql:
    build:
      context: ./docker/database
    environment:
      - MYSQL_ROOT_PASSWORD=symf0nyTest
    restart: on-failure

  php:
    build:
      context: ./docker/php-fpm
    volumes:
      - ./dashboard:/var/www/dashboard
      - ./docker/php-fpm/php-ini-local.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - mysql
    restart: on-failure

  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./dashboard:/var/www/dashboard
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites:/etc/nginx/sites-available
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
      - mysql
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
